language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
install:
    - "pip install geopandas>=0.7.0"
    - "pip install -e ."
    - "pip install pygeos pytest pytest-cov pytest-benchmark"
    - "pip install coveralls>=1.1"
script: "pytest --cov geofeather --cov-report term-missing"
after_success:
    - coveralls || echo "!! intermittent coveralls failure"
